---
#------------------------------------------------------------------------------------------------------
# Purpose:
#------------------------------------------------------------------------------------------------------
# This file defines the Kustomization component for the development environment.
# It includes resources and patches that override or extend the base configuration for dev-specific needs.
#------------------------------------------------------------------------------------------------------
# Checklist for developers using this Kustomization file
#------------------------------------------------------------------------------------------------------
# 1. Ensure all listed resources (e.g., configmap.yaml) are required for the development environment.
# 2. Add or remove resources/patches based on the specific requirements of your service.
#------------------------------------------------------------------------------------------------------

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: configmap.yaml
